import i18n, { i18nRender } from '@/locales/index'

const ERROR_MESSAGE = {
  USER_ROLE_IS_REQUIRED: 11,
  USER_IS_DISABLED: 12,
  AUTHORIZATION_HEADER_NOT_ALLOWED_WHEN_LOGIN: 13,
  REQUEST_TOKEN_ERROR: 14,
  TOKEN_IS_NOT_VALID: 15,
  LOGIN_HAS_EXPIRED_PLEASE_LOGIN_AGAIN: 16,
  USER_HAS_NO_PERMISSION: 17,
  USERNAME_DOESNT_EXIST_PLEASE_ENTER_CORRECT_USERNAME: 18,
  USERNAME_AND_PASSWORD_ARE_NOT_MATCHED_PLEASE_ENTER_CORRECT_PASSWORD: 19,
  USER_IS_DISABLED2: 1010,
  YOU_DO_NOT_HAVE_ANY_IP_ADDRESS_WHITELISTED_PLEASE_CONTACT_THE_ADMINISTRATOR: 1011,
  YOU_ARE_NOT_ALLOWED_TO_ACCESS_THIS_SITE_USING_YOUR_CURRENT_NETWORK_PLEASE_CONTACT_THE_ADMINISTRATOR: 22,
  YOU_ARE_NOT_ALLOWED_TO_ACCESS_THIS_SITE_USING_YOUR_CURRENT_NETWORK_PLEASE_CONTACT_THE_ADMINISTRATOR2: 20,
  ERROR_IN_GENERATING_NEW_ACCESS_TOKEN: 1013,
  LOGOUT_IS_SUCCESSFUL: 1014,
  LOGIN_IS_SUCCESSFUL: 1015,
  YOUR_ACCOUNT_IS_DISABLED_PLEASE_CONTACT_THE_ADMINISTRATOR: 26,
  ACCOUNT_OR_PASSWORD_OAUTH_ERROR_PLEASE_CHECK_KEYCLOAK_ACCOUNT_OR_PASSWORD_PARAMETER: 1017,
  ONE_TIME_PASSWORD_NOT_VALID: 1018,
  INCORRECT_CODE_ENTERED_PLEASE_ENTER_THE_CORRECT_CODE: 29,
  THE_QR_IMAGE_NOT_YET_SCANNED: 1020,
  THERE_IS_ERROR_IN_GENERATING_QR_CODE_IMAGE: 1021,
  THE_QR_USERNAME_DOES_NOT_EXIST_PLEASE_CHECK_THE_USERNAME_PARAMETER: 1022,
  NEW_PASSWORD_IS_THE_SAME_AS_THE_OLD_PASSWORD_PLEASE_ENTER_A_DIFFERENT_PASSWORD: 33,
  THE_QR_IMAGE_ALREADY_EXIST: 1024,
  THE_APPLICATION_TYPE_IS_NOT_ALLOWED: 35,
  REQUEST_IS_EMPTY: 2001,
  REQUEST_JSON_IS_ERROR: 2002,
  SERVER_HAS_ERROR: 2003,
  DATABASE_HAS_ERROR: 2004,
  PASSWORD_SHOULD_BE_8_16_CHARACTERS: 31,
  USERNAME_ALREADY_EXIST: 41,
  THE_USER_DOES_NOT_EXIST: 42,
  THE_USER_USERTYPE_CANNOT_BE_CHANGED: 43,
  USERNAME_ALREADY_EXISTS_PLEASE_ENTER_VALID_USERNAME: 44,
  USER_PARENT_IS_REQUIRED: 45,
  USER_PARENT_VALUE_IS_INVALID: 46,
  PLATFORM_ALREADY_EXISTS_PLEASE_ENTER_VALID_PLATFORM: 47,
  INVALID_IP_ADDRESS_DETECTED: 48,
  THE_PARENT_TYPE_IS_NOT_THE_SAME_WITH_USER_TYPE: 49,
  THE_USER_PARENTTYPE_CANNOT_BE_CHANGED: 4010,
  THE_USER_PARENT_CANNOT_BE_CHANGED: 4011,
  THE_ROLE_DOES_NOT_EXIST: 5001,
  THE_ROLE_CODE_ALREADY_EXISTS_PLEASE_ENTER_VALID_CODE: 5002,
  THE_ROLE_NAME_ALREADY_EXISTS_PLEASE_ENTER_VALID_NAME: 5003,
  INVALID_USER_TYPE_PARAMETER_PLEASE_ENTER_A_VALID_USER_TYPE: 5004,
  THE_ACCESS_LOG_ALREADY_EXIST: 6001,
  THE_ACCESS_LOG_DOES_NOT_EXIST: 6002,
  THE_A_LOG_ALREADY_EXIST: 7001,
  THE_ACCESS_LOG_DOES_NOT_EXIST2: 7002,
  MERCHANT_EXIST: 10001,
  MERCHANT_NO_EXIST: 10002,
  PAYMENT_CURRENCYDOES_NOT_EXIST: 13001,
  AMOUNT_NOT_VALID: 13002,
  THE_SYS_CURRENCY_DOES_NOT_EXIST: 14001,
  PAYMENT_ORDER_DO_NOT_EXIST: 15001,
  PAYMENT_CURRENCY_ALREADY_EXIST: 16001,
  PAYMENT_CURRENCY_DOES_NOT_EXIST: 16002,
  MERCHANT_RATE_ALREADY_EXIST: 17001,
  MERCHANT_RATE_DOES_NOT_EXIST: 17002,
  NAME_ALREADY_EXISTS: 141
}

const ERROR_MESSAGE_LANG_MESSAGE = {
  [ERROR_MESSAGE.USER_ROLE_IS_REQUIRED]: 'messages.USER_ROLE_IS_REQUIRED',
  [ERROR_MESSAGE.USER_IS_DISABLED]: 'messages.USER_IS_DISABLED',
  [ERROR_MESSAGE.AUTHORIZATION_HEADER_NOT_ALLOWED_WHEN_LOGIN]: 'messages.AUTHORIZATION_HEADER_NOT_ALLOWED_WHEN_LOGIN',
  [ERROR_MESSAGE.REQUEST_TOKEN_ERROR]: 'messages.AUTHORIZATION_HEADER_NOT_ALLOWED_WHEN_LOGIN',
  [ERROR_MESSAGE.TOKEN_IS_NOT_VALID]: 'messages.TOKEN_IS_NOT_VALID',
  [ERROR_MESSAGE.LOGIN_HAS_EXPIRED_PLEASE_LOGIN_AGAIN]: 'messages.LOGIN_HAS_EXPIRED_PLEASE_LOGIN_AGAIN',
  [ERROR_MESSAGE.USER_HAS_NO_PERMISSION]: 'messages.LOGIN_HAS_EXPIRED_PLEASE_LOGIN_AGAIN',
  [ERROR_MESSAGE.USERNAME_DOESNT_EXIST_PLEASE_ENTER_CORRECT_USERNAME]:
    'messages.USERNAME_DOESNT_EXIST_PLEASE_ENTER_CORRECT_USERNAME',
  [ERROR_MESSAGE.USERNAME_AND_PASSWORD_ARE_NOT_MATCHED_PLEASE_ENTER_CORRECT_PASSWORD]:
    'messages.USERNAME_AND_PASSWORD_ARE_NOT_MATCHED_PLEASE_ENTER_CORRECT_PASSWORD',
  [ERROR_MESSAGE.USER_IS_DISABLED2]: 'messages.USER_IS_DISABLED2',
  [ERROR_MESSAGE.YOU_DO_NOT_HAVE_ANY_IP_ADDRESS_WHITELISTED_PLEASE_CONTACT_THE_ADMINISTRATOR]:
    'messages.YOU_DO_NOT_HAVE_ANY_IP_ADDRESS_WHITELISTED_PLEASE_CONTACT_THE_ADMINISTRATOR',
  [ERROR_MESSAGE.YOU_ARE_NOT_ALLOWED_TO_ACCESS_THIS_SITE_USING_YOUR_CURRENT_NETWORK_PLEASE_CONTACT_THE_ADMINISTRATOR]:
    'messages.YOU_ARE_NOT_ALLOWED_TO_ACCESS_THIS_SITE_USING_YOUR_CURRENT_NETWORK_PLEASE_CONTACT_THE_ADMINISTRATOR',
  [ERROR_MESSAGE.YOU_ARE_NOT_ALLOWED_TO_ACCESS_THIS_SITE_USING_YOUR_CURRENT_NETWORK_PLEASE_CONTACT_THE_ADMINISTRATOR2]:
    'messages.YOU_ARE_NOT_ALLOWED_TO_ACCESS_THIS_SITE_USING_YOUR_CURRENT_NETWORK_PLEASE_CONTACT_THE_ADMINISTRATOR',
  [ERROR_MESSAGE.ERROR_IN_GENERATING_NEW_ACCESS_TOKEN]: 'messages.ERROR_IN_GENERATING_NEW_ACCESS_TOKEN',
  [ERROR_MESSAGE.LOGOUT_IS_SUCCESSFUL]: 'messages.LOGOUT_IS_SUCCESSFUL',
  [ERROR_MESSAGE.LOGIN_IS_SUCCESSFUL]: 'messages.LOGIN_IS_SUCCESSFUL',
  [ERROR_MESSAGE.YOUR_ACCOUNT_IS_DISABLED_PLEASE_CONTACT_THE_ADMINISTRATOR]:
    'messages.YOUR_ACCOUNT_IS_DISABLED_PLEASE_CONTACT_THE_ADMINISTRATOR',
  [ERROR_MESSAGE.ACCOUNT_OR_PASSWORD_OAUTH_ERROR_PLEASE_CHECK_KEYCLOAK_ACCOUNT_OR_PASSWORD_PARAMETER]:
    'messages.ACCOUNT_OR_PASSWORD_OAUTH_ERROR_PLEASE_CHECK_KEYCLOAK_ACCOUNT_OR_PASSWORD_PARAMETER',
  [ERROR_MESSAGE.ONE_TIME_PASSWORD_NOT_VALID]: 'messages.ONE_TIME_PASSWORD_NOT_VALID',
  [ERROR_MESSAGE.INCORRECT_CODE_ENTERED_PLEASE_ENTER_THE_CORRECT_CODE]:
    'messages.INCORRECT_CODE_ENTERED_PLEASE_ENTER_THE_CORRECT_CODE',
  [ERROR_MESSAGE.THE_QR_IMAGE_NOT_YET_SCANNED]: 'messages.THE_QR_IMAGE_NOT_YET_SCANNED',
  [ERROR_MESSAGE.THERE_IS_ERROR_IN_GENERATING_QR_CODE_IMAGE]: 'messages.THERE_IS_ERROR_IN_GENERATING_QR_CODE_IMAGE',
  [ERROR_MESSAGE.THE_QR_USERNAME_DOES_NOT_EXIST_PLEASE_CHECK_THE_USERNAME_PARAMETER]:
    'messages.THE_QR_USERNAME_DOES_NOT_EXIST_PLEASE_CHECK_THE_USERNAME_PARAMETER',
  [ERROR_MESSAGE.NEW_PASSWORD_IS_THE_SAME_AS_THE_OLD_PASSWORD_PLEASE_ENTER_A_DIFFERENT_PASSWORD]:
    'messages.NEW_PASSWORD_IS_THE_SAME_AS_THE_OLD_PASSWORD_PLEASE_ENTER_A_DIFFERENT_PASSWORD',
  [ERROR_MESSAGE.THE_QR_IMAGE_ALREADY_EXIST]: 'messages.THE_QR_IMAGE_ALREADY_EXIST',
  [ERROR_MESSAGE.THE_APPLICATION_TYPE_IS_NOT_ALLOWED]: 'messages.THE_APPLICATION_TYPE_IS_NOT_ALLOWED',
  [ERROR_MESSAGE.REQUEST_IS_EMPTY]: 'messages.REQUEST_IS_EMPTY',
  [ERROR_MESSAGE.REQUEST_JSON_IS_ERROR]: 'messages.REQUEST_JSON_IS_ERROR',
  [ERROR_MESSAGE.SERVER_HAS_ERROR]: 'messages.SERVER_HAS_ERROR',
  [ERROR_MESSAGE.DATABASE_HAS_ERROR]: 'messages.DATABASE_HAS_ERROR',
  [ERROR_MESSAGE.PASSWORD_SHOULD_BE_8_16_CHARACTERS]: 'messages.PASSWORD_SHOULD_BE_8_16_CHARACTERS',
  [ERROR_MESSAGE.USERNAME_ALREADY_EXIST]: 'messages.USERNAME_ALREADY_EXIST',
  [ERROR_MESSAGE.THE_USER_DOES_NOT_EXIST]: 'messages.THE_USER_DOES_NOT_EXIST',
  [ERROR_MESSAGE.THE_USER_USERTYPE_CANNOT_BE_CHANGED]: 'messages.THE_USER_USERTYPE_CANNOT_BE_CHANGED',
  [ERROR_MESSAGE.USERNAME_ALREADY_EXISTS_PLEASE_ENTER_VALID_USERNAME]:
    'messages.USERNAME_ALREADY_EXISTS_PLEASE_ENTER_VALID_USERNAME',
  [ERROR_MESSAGE.USER_PARENT_IS_REQUIRED]: 'messages.USER_PARENT_IS_REQUIRED',
  [ERROR_MESSAGE.USER_PARENT_VALUE_IS_INVALID]: 'messages.USER_PARENT_VALUE_IS_INVALID',
  [ERROR_MESSAGE.PLATFORM_ALREADY_EXISTS_PLEASE_ENTER_VALID_PLATFORM]:
    'messages.PLATFORM_ALREADY_EXISTS_PLEASE_ENTER_VALID_PLATFORM',
  [ERROR_MESSAGE.INVALID_IP_ADDRESS_DETECTED]: 'messages.INVALID_IP_ADDRESS_DETECTED',
  [ERROR_MESSAGE.THE_PARENT_TYPE_IS_NOT_THE_SAME_WITH_USER_TYPE]:
    'messages.THE_PARENT_TYPE_IS_NOT_THE_SAME_WITH_USER_TYPE',
  [ERROR_MESSAGE.THE_USER_PARENTTYPE_CANNOT_BE_CHANGED]: 'messages.THE_USER_PARENTTYPE_CANNOT_BE_CHANGED',
  [ERROR_MESSAGE.THE_USER_PARENT_CANNOT_BE_CHANGED]: 'messages.THE_USER_PARENT_CANNOT_BE_CHANGED',
  [ERROR_MESSAGE.THE_ROLE_DOES_NOT_EXIST]: 'messages.THE_ROLE_DOES_NOT_EXIST',
  [ERROR_MESSAGE.THE_ROLE_CODE_ALREADY_EXISTS_PLEASE_ENTER_VALID_CODE]:
    'messages.THE_ROLE_CODE_ALREADY_EXISTS_PLEASE_ENTER_VALID_CODE',
  [ERROR_MESSAGE.THE_ROLE_NAME_ALREADY_EXISTS_PLEASE_ENTER_VALID_NAME]:
    'messages.THE_ROLE_NAME_ALREADY_EXISTS_PLEASE_ENTER_VALID_NAME',
  [ERROR_MESSAGE.INVALID_USER_TYPE_PARAMETER_PLEASE_ENTER_A_VALID_USER_TYPE]:
    'messages.INVALID_USER_TYPE_PARAMETER_PLEASE_ENTER_A_VALID_USER_TYPE',
  [ERROR_MESSAGE.THE_ACCESS_LOG_ALREADY_EXIST]: 'messages.THE_ACCESS_LOG_ALREADY_EXIST',
  [ERROR_MESSAGE.THE_ACCESS_LOG_DOES_NOT_EXIST]: 'messages.THE_ACCESS_LOG_DOES_NOT_EXIST',
  [ERROR_MESSAGE.THE_A_LOG_ALREADY_EXIST]: 'messages.THE_A_LOG_ALREADY_EXIST',
  [ERROR_MESSAGE.THE_ACCESS_LOG_DOES_NOT_EXIST2]: 'messages.THE_ACCESS_LOG_DOES_NOT_EXIST2',
  [ERROR_MESSAGE.MERCHANT_EXIST]: 'messages.MERCHANT_EXIST',
  [ERROR_MESSAGE.MERCHANT_NO_EXIST]: 'messages.MERCHANT_NO_EXIST',
  [ERROR_MESSAGE.PAYMENT_CURRENCYDOES_NOT_EXIST]: 'messages.PAYMENT_CURRENCYDOES_NOT_EXIST',
  [ERROR_MESSAGE.AMOUNT_NOT_VALID]: 'messages.AMOUNT_NOT_VALID',
  [ERROR_MESSAGE.THE_SYS_CURRENCY_DOES_NOT_EXIST]: 'messages.THE_SYS_CURRENCY_DOES_NOT_EXIST',
  [ERROR_MESSAGE.PAYMENT_ORDER_DO_NOT_EXIST]: 'messages.PAYMENT_ORDER_DO_NOT_EXIST',
  [ERROR_MESSAGE.PAYMENT_CURRENCY_ALREADY_EXIST]: 'messages.PAYMENT_CURRENCY_ALREADY_EXIST',
  [ERROR_MESSAGE.PAYMENT_CURRENCY_DOES_NOT_EXIST]: 'messages.PAYMENT_CURRENCY_DOES_NOT_EXIST',
  [ERROR_MESSAGE.MERCHANT_RATE_ALREADY_EXIST]: 'messages.MERCHANT_RATE_ALREADY_EXIST',
  [ERROR_MESSAGE.MERCHANT_RATE_DOES_NOT_EXIST]: 'messages.MERCHANT_RATE_DOES_NOT_EXIST',
  [ERROR_MESSAGE.NAME_ALREADY_EXISTS]: 'messages.NAME_ALREADY_EXISTS'
}

export const errorMessage = (msg) => {
  return ERROR_MESSAGE_LANG_MESSAGE[msg] && i18n.locale === 'zh-CN' ? i18nRender(ERROR_MESSAGE_LANG_MESSAGE[msg]) : null
}
